project:
  type: book
  execute-dir: project
toc: true
number-sections: false
bibliography: 2023 references.bib
highlight-style: pygments

book:
  title: "***THE ROLE OF DATA ANALYSIS IN SCHOOL DISTRICT LEADERSHIP***"
  subtitle: "*~~28~~ 29 Years of Growth and Accomplishment at SCUC-ISD as Context for Today's Decisions*"
  author: "Dan Swart, CPA (retired)"
  date: "June 5, 2025"
  reader-mode: true
  search: true
  downloads: [pdf, docx, epub]
  description: "Improved Data Analysis Tools for School Districts"
  keyword: Schertz, Cibolo, Universal City, ISD, performance, run chart, history, continuous improvement, control charts, data analysis
  url: https://29yearsofdatascuc.netlify.app/
  sidebar:
    search: true
    collapse-level: 3
    pinned: true
  repo-url: https://github.com/danswart/29-Years-of-Data-SCUC
  # repo-subdir: _book
  # repo-branch: master
  repo-actions: [edit, issue, source]
  sharing: [twitter, facebook, linkedin]
  image: unique-1-yellow-locker.jpg
  # comments:
  #  giscus:
  #    repo: danswart/29-Years-of-Data-SCUC
  open-graph:
    image: https://github.com/danswart/29-Years-of-Data-SCUC/unique-1-yellow-locker.jpg
    description: A compilation of 29 years of TEA data for the SCUC-ISD.
  page-footer:
    left: |
      This book was written by Dan Swart, CPA (ret) while serving as Trustee (Place 6), SCUC-ISD
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: unique-1-yellow-locker.jpg
  favicon: unique-1-yellow-locker.jpg

  chapters:
    - index.qmd

    - 2023 dedication.qmd

    - 2023 acknowledgements.qmd

    - 2023 how_to_use.qmd

    - 2023 forthestatisticallycurious.qmd

    - part: "District Performance"
      chapters:
        - 2023 district_perform.qmd

    - part: "Students"
      chapters:
        - 2023 student_demo.qmd

    - part: "Standardized Scores"
      chapters:
        - 2023 STAAR Scores by Subject.qmd
        - 2023 STAAR Scores by Student Grouping.qmd
        - 2023 sat_act.qmd

    - part: "Personnel"
      chapters:
        - 2023 teachers.qmd
        - 2023 staff.qmd

    - part: "Finances"
      chapters:
       - 2023 taxes_and_revenues.qmd
       - 2023 expenses.qmd



format:
  html:
    css: [swart-20250327.css, tachyons.min.css, r-colors.css]
    theme:
      - cosmo
    grid:
      sidebar-width: 500px  # Increase this value to make the sidebar wider
      body-width: 700px     # Decrease this value to make the main content area smaller
      margin-width: 500px
    max-width: 2400px # Increase this value to make the overall page wider
    fontsize: 14pt # Adjust this value to increase or decrease the base font sizeself-contained: true
    embed-resources: false
    html-math-method: katex
    callout-appearance: simple

  pdf:
    documentclass: scrbook
    include-in-header: preamble.tex
    classoption: 16pt
    includes:
      in_header: latex/preamble.tex
      before_body: latex/before_body.tex
      after_body: latex/after_body.tex
      colorlinks: true
    fontsize: 12pt
    fontfamily: palatino
    margin-left: 10mm
    margin-right: 10mm
    before_body: latex/before_body.tex
    after_body: latex/after_body.tex
    keep_tex: true
    dev: "cairo_pdf"
    latex_engine: xelatex
    citation_package: natbib
    pandoc_args: ["--top-level-division=chapter", "--lua-filter=latex/sidebar.lua"]
    quote_footer: ["\\hspace*{\\fill} ", ""]
    toc_unnumbered: true
    number_sections: false
    header-includes:
    - \usepackage{geometry}
    - \geometry{top=1.00in,left=.50in,bottom=1.00in,right=.50in}
    - \setlength\parindent{0.25in}
    - \usepackage{xcolor}
    - \usepackage{tcolorbox}
    - \usepackage{ragged2e}
    - \usepackage{hyperref}
    - \usepackage{float}
    - \hypersetup{colorlinks=true, linkcolor=MidnightBlue, urlcolor=BlueViolet, citecolor=BrickRed}
    - \urlstyle{same}
    - \graphicspath{{pbc}{img}}
    - \usepackage{caption}
    - \captionsetup[figure]{font=Large}
    - \captionsetup{font=Large}
    - \usepackage{longtable}
    - \usepackage{placeins}
linestretch: 1
fontsize: 18pt
knitr:
  opts_chunk:
    echo: false
    error: false
    warning: false
    message: false

